/* ELSE IF */
DELIMITER //
CREATE PROCEDURE `PRODUTO_TIPO`(VPRODUTO VARCHAR(50))
BEGIN
	DECLARE VPRECO FLOAT;
    DECLARE VMENSAGEM VARCHAR(30);
    SELECT PRECO_DE_LISTA INTO VPRECO FROM tabela_de_produtos
    WHERE CODIGO_DO_PRODUTO = VPRODUTO;
    IF VPRECO >= 12 THEN
		SET VMENSAGEM = 'PRODUTO CARO';
	ELSEIF VPRECO >= 7 AND VPRECO < 12 THEN
		SET VMENSAGEM = 'PRODUTO EM CONTA';
	ELSE
		SET VMENSAGEM = 'PRODUTO BARATO';
	END IF;
    
    SELECT VMENSAGEM;

END //


/* CASE CONDICIONAL */
DELIMITER //
CREATE PROCEDURE `PRODUTO_TIPO_CASE`(VPRODUTO VARCHAR(50))
BEGIN
	DECLARE VPRECO FLOAT;
    DECLARE VMENSAGEM VARCHAR(30);
    SELECT PRECO_DE_LISTA INTO VPRECO FROM tabela_de_produtos
    WHERE CODIGO_DO_PRODUTO = VPRODUTO;
    CASE
    WHEN VPRECO >= 12 THEN 
		SET VMENSAGEM = 'PRODUTO CARO';
	WHEN VPRECO >= 7 AND VPRECO < 12 THEN
		SET VMENSAGEM = 'PRODUTO EM CONTA';
	WHEN VPRECO < 7 THEN
		SET VMENSAGEM = 'PRODUTO BARATO';
	END CASE;
    
    SELECT VMENSAGEM;

END //

CALL PRODUTO_TIPO_CASE('1004327');