/* CASE */
DELIMITER //
CREATE PROCEDURE `PROC_TIPO_SABOR` (VPRODUTO VARCHAR(50))
BEGIN
	
    DECLARE VSABOR VARCHAR(50);
	SELECT SABOR INTO VSABOR FROM tabela_de_produtos WHERE CODIGO_DO_PRODUTO = VPRODUTO;

	CASE VSABOR
    WHEN 'Lima/Limão' THEN SELECT 'Citrico';
    WHEN 'Laranja' THEN SELECT 'Citrico';
	WHEN 'Morango/Limão' THEN SELECT 'Citrico';
	WHEN 'Uva' THEN SELECT 'Neutro';
	WHEN 'Morango' THEN SELECT 'Neutro';
    ELSE SELECT 'Acidos';
    END CASE;
    
END //

SELECT * FROM tabela_de_produtos;

CALL PROC_TIPO_SABOR('1004327');
CALL PROC_TIPO_SABOR2('1004327');

/* CASE NOT FOUND */
DELIMITER //
CREATE PROCEDURE `PROC_TIPO_SABOR2` (VPRODUTO VARCHAR(50))
BEGIN
	
    DECLARE VSABOR VARCHAR(50);
    DECLARE MSG_ERRO VARCHAR(30);
    DECLARE CONTINUE HANDLER FOR 1339 SET MSG_ERRO = 'O CASE NAO ESTA COMPLETO';
	SELECT SABOR INTO VSABOR FROM tabela_de_produtos WHERE CODIGO_DO_PRODUTO = VPRODUTO;

	CASE VSABOR
    WHEN 'Lima/Limão' THEN SELECT 'Citrico';
    WHEN 'Laranja' THEN SELECT 'Citrico';
	WHEN 'Morango/Limão' THEN SELECT 'Citrico';
	WHEN 'Uva' THEN SELECT 'Neutro';
	WHEN 'Morango' THEN SELECT 'Neutro';
    END CASE;
    SELECT MSG_ERRO;
END //


