/*  FUNÇÕES STRING */
SELECT LTRIM('       OLÁ')  AS TEXTO;
SELECT TRIM('     OLÁ   ') AS TEXTO;
SELECT RTRIM('OLÁ       ') AS TEXTO;

SELECT CONCAT('OLÁ', ' ', ' TUDO BEM', '?') AS RESULTADO;

SELECT UPPER('olá, tudo bem?') AS RESULTADO;
SELECT SUBSTRING('OLÁ, TUDO BEM?', 6) AS RESULTADO;
SELECT SUBSTRING('OLÁ, TUDO BEM?', 6, 4) AS RESULTADO;

SELECT CONCAT(NOME, ' (',CPF,') ') AS RESULTADO FROM tabela_de_clientes;

/* FUNÇÕES DE DATA */
SELECT ADDDATE('2020-02-12', 330);

SELECT CURRENT_DATE();
SELECT CURRENT_TIME();
SELECT CURRENT_TIMESTAMP();

SELECT DATEDIFF('2021-01-01', '2020-11-12') AS DIAS_FIM_ANO;
SELECT DATEDIFF(CURRENT_TIMESTAMP(), '1996-11-03 12:53:00') AS DIAS_VIDA;

SELECT DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 5 DAY) AS RESULTADO;

SELECT DAYNAME('2020-11-12') AS DIA_SEMANA;

/* FUNÇÕES NUMERICAS */
SELECT CEILING(12.3232323232) AS RESULTADO; /* MAIOR INTEIRO */
SELECT ROUND(12.3232323232) AS RESULTADO;  /* ARREDONDA ACIMA DE 5*/
SELECT FLOOR(12.3232323232) AS RESULTADO; /* MENOR INTEIRO */

SELECT RAND() AS RESULTADO; /* NUMERO ALEATORIO */

SELECT NUMERO, QUANTIDADE, PRECO, ROUND(QUANTIDADE * PRECO, 3) AS FATURAMENTO FROM itens_notas_fiscais;

/* CONVERSAO */
SELECT CONCAT('O DIA DE HOJE É: ', CURRENT_TIMESTAMP()) AS RESULTADO;

SELECT CONCAT('O DIA DE HOJE É: ', DATE_FORMAT(CURRENT_TIMESTAMP(), '%d/%m/%Y')) AS RESULTADO;