/* INCLUINDO VENDA */

SELECT FUNC_PRODUTO_ALEATORIO(), FUNC_VENDEDOR_ALEATORIO(), FUNC_CLIENTE_ALEATORIO();


DELIMITER //
CREATE PROCEDURE `INSERE_VENDA_ALEATORIA` (VDATA DATE, VMAX_ITENS INT, VMAX_QUANTIDADE INT)
BEGIN
	DECLARE VPRODUTO VARCHAR(10);
    DECLARE VCLIENTE VARCHAR(11);
    DECLARE VVENDEDOR VARCHAR(5);
    DECLARE VQUANTIDADE INT;
    DECLARE VPRECO FLOAT;
    DECLARE VITENS INT;
    DECLARE VNUMERO INT;
    DECLARE VCONTADOR INT DEFAULT 1;
    DECLARE VNUMITENSNOTA INT;
    
    SELECT MAX(NUMERO) + 1 INTO VNUMERO FROM notas_fiscais;
        
    SET VCLIENTE = FUNC_CLIENTE_ALEATORIO();
    SET VVENDEDOR = FUNC_VENDEDOR_ALEATORIO();
	SET VITENS = FUNC_NUMERO_ALEATORIO(1, VMAX_ITENS);

	INSERT INTO notas_fiscais (CPF, MATRICULA, DATA_VENDA, NUMERO, IMPOSTO)
    VALUES(VCLIENTE, VVENDEDOR, VDATA, VNUMERO, 0.18);
    
	WHILE VCONTADOR <= VITENS
    DO
		SET VPRODUTO = FUNC_PRODUTO_ALEATORIO();
        
        /* QUANTOS ITENS INCLUIDOS COM ESSE CODIGO DE PRODUTO */
        SELECT COUNT(*) INTO VNUMITENSNOTA FROM itens_notas_fiscais
        WHERE NUMERO = VNUMERO AND CODIGO_DO_PRODUTO = VPRODUTO;
        
        IF(VNUMITENSNOTA = 0) THEN
			SET VQUANTIDADE = FUNC_NUMERO_ALEATORIO(2, VMAX_QUANTIDADE);
			SELECT PRECO_DE_LISTA INTO VPRECO FROM tabela_de_produtos WHERE CODIGO_DO_PRODUTO = VPRODUTO;
        
			INSERT INTO itens_notas_fiscais(NUMERO, CODIGO_DO_PRODUTO, QUANTIDADE, PRECO)
			VALUES(VNUMERO, VPRODUTO, VQUANTIDADE, VPRECO);
        END IF;      
        SET VCONTADOR = VCONTADOR + 1;
    END WHILE;
    
END //


CALL INSERE_VENDA_ALEATORIA('2021-11-16', 3, 8);

SELECT * FROM NOTAS_FISCAIS WHERE DATA_VENDA = '2021-11-16';
SELECT * FROM ITENS_NOTAS_FISCAIS WHERE NUMERO = 87979;