/* CRIANDO NUMEROS ALEATORIOS */
SELECT RAND();

-- (ALEATORIO() * (MAX-MIN+1)) + MIN
SELECT (RAND() * (300-15+1)) + 15 AS RESULTADO;

-- PARTE INTEIRA
SELECT FLOOR(RAND() * (300-15+1)) + 15 AS RESULTADO;

/* FUNÇÃO NUMERO ALEATORIO */
DELIMITER //
CREATE FUNCTION `FUNC_NUMERO_ALEATORIO`(MIN INT, MAX INT)
RETURNS INTEGER
BEGIN
	DECLARE VRETORNO INT;	
	SELECT FLOOR(RAND() * (MAX-MIN+1)) + MIN AS RESULTADO INTO VRETORNO;    
	RETURN VRETORNO;
END //

SELECT FUNC_NUMERO_ALEATORIO(150,2);


/* CLIENTE ALEATORIO */
DELIMITER //
CREATE FUNCTION `FUNC_CLIENTE_ALEATORIO`()
RETURNS VARCHAR(11)
BEGIN
	DECLARE VRETORNO VARCHAR(11);
    DECLARE MAXTABELA INT;
    DECLARE VALEATORIO INT;
    
    SELECT COUNT(*) INTO MAXTABELA FROM tabela_de_clientes;
    SET VALEATORIO = FUNC_NUMERO_ALEATORIO(1,MAXTABELA);
    SET VALEATORIO = VALEATORIO - 1;
	SELECT CPF INTO VRETORNO FROM tabela_de_clientes LIMIT VALEATORIO,1;
    
	RETURN VRETORNO;
END //

SELECT FUNC_CLIENTE_ALEATORIO();

DELIMITER //
CREATE FUNCTION `FUNC_PRODUTO_ALEATORIO`()
RETURNS VARCHAR(11)
BEGIN
	DECLARE VRETORNO VARCHAR(11);
    DECLARE MAXTABELA INT;
    DECLARE VALEATORIO INT;
    
    SELECT COUNT(*) INTO MAXTABELA FROM tabela_de_produtos;
    SET VALEATORIO = FUNC_NUMERO_ALEATORIO(1,MAXTABELA);
    SET VALEATORIO = VALEATORIO - 1;
	SELECT CODIGO_DO_PRODUTO INTO VRETORNO FROM tabela_de_produtos LIMIT VALEATORIO,1;
    
	RETURN VRETORNO;
END //

SELECT FUNC_PRODUTO_ALEATORIO();

DELIMITER //
CREATE FUNCTION `FUNC_VENDEDOR_ALEATORIO`()
RETURNS VARCHAR(11)
BEGIN
	DECLARE VRETORNO VARCHAR(11);
    DECLARE MAXTABELA INT;
    DECLARE VALEATORIO INT;
    
    SELECT COUNT(*) INTO MAXTABELA FROM tabela_de_vendedores;
    SET VALEATORIO = FUNC_NUMERO_ALEATORIO(1,MAXTABELA);
    SET VALEATORIO = VALEATORIO - 1;
	SELECT MATRICULA INTO VRETORNO FROM tabela_de_vendedores LIMIT VALEATORIO,1;
    
	RETURN VRETORNO;
END //

SELECT FUNC_VENDEDOR_ALEATORIO();