/*CRIAR BANCO*/
CREATE DATABASE sucos;

/*EXCLUIR BANCO*/
DROP DATABASE sucos;

/*CRIAR TABELAS*/
CREATE TABLE tbCliente
(
	CPF VARCHAR(11),
    NOME VARCHAR(100),
    ENDERECO_1 VARCHAR(150),
    ENDERECO_2 VARCHAR(150),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(50),
    CEP VARCHAR(8),
	IDADE SMALLINT,
    SEXO VARCHAR(1),
    LIMITE_CREDITO FLOAT,
    VOLUME_COMPRA FLOAT,
    PRIMEIRA_COMPRA BIT(1)
);

CREATE TABLE tbVendedor
(
	MATRICULA VARCHAR(5),
    NOME VARCHAR(100),
    PERCENTUAL_COMISSAO FLOAT
);


CREATE TABLE tbProduto
(
	PRODUTO VARCHAR(20) NULL,
    NOME VARCHAR(150) NULL,
    EMBALAGEM VARCHAR(50) NULL,
    TAMANHO VARCHAR(50) NULL,
    SABOR VARCHAR(50) NULL,
    PRECO FLOAT NULL
);


/*INSERINDO REGISTROS*/
INSERT INTO tbProduto 
(PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO)
VALUES
('1040108','light - 350ml - melancia','lata','350ml', 'melancia', 4.56);

/*VISUALIZAR TABELA*/
SELECT * FROM tbProduto;
SELECT * FROM tbVendedor;

INSERT INTO tbVendedor
(MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
('00233', 'João Geraldo da Fonseca', 0.10);

/*INSERIR VARIOS REGISTROS DE UMA VEZ*/
INSERT INTO tbProduto 
(PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO)
VALUES
('1040107','clean - 2 litros - laranja','pet','2l', 'laranja', 16.01),
('1037797','sabor da montanha - 700ml - uva','garrafa','700ml', 'uva', 6.31),
('1000889','videira do campo - 1,5 litros - melancia','pet','1,5l', 'melancia', 19.51);

INSERT INTO tbVendedor
(MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
('00235', 'Márcio Almeida Silva', 0.08),
('00236', 'Cláudia Morais', 0.08);


INSERT INTO tbproduto (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO) VALUES
('544931', 'frescor do verão - 350ml - limao', 'pet', '350ml','limao',3.20);

INSERT INTO tbproduto (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO) VALUES
('1078680', 'frescor do verao - 470ml - manga', 'lata', '470ml','manga',5.18);


/*ALTERAR REGISTROS EM TABELAS*/
UPDATE tbProduto
SET EMBALAGEM = 'lata',
PRECO = 2.46 
WHERE PRODUTO = '544931';

UPDATE tbProduto
SET EMBALAGEM = 'garrafa'
WHERE PRODUTO = '1078680';

/*INCLUINDO CHAVE PRIMARIA NÃO DEFINIDA NA CRIAÇÃO DA TABELA*/
ALTER TABLE tbProduto
ADD PRIMARY KEY (PRODUTO);

ALTER TABLE tbCliente
ADD PRIMARY KEY (CPF);

ALTER TABLE tbVendedor
ADD PRIMARY KEY (MATRICULA);

/*ADICIONANDO COLUNAS EM TABELAS JÁ CRIADAS*/
ALTER TABLE tbCliente
ADD COLUMN (DATA_NASCIMENTO DATE);

ALTER TABLE tbVendedor
ADD COLUMN (DATA_ADMISSAO DATE);

ALTER TABLE tbVendedor
ADD COLUMN (DE_FERIAS VARCHAR(1));

INSERT INTO tbCliente
(CPF, NOME, ENDERECO_1, ENDERECO_2, BAIRRO, CIDADE, ESTADO, CEP, IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA, DATA_NASCIMENTO)
VALUES ('23615202512','João da Silva','Rua projetada A número 10','','vila Roman','Caxias','Amazonas','33333333',30,'M',10000.00,2000,0,'1989-12-25');

UPDATE tbvendedor
SET DATA_ADMISSAO = '2018-08-21',
DE_FERIAS = 'N'
WHERE MATRICULA = '00233';



