SELECT * FROM itens_notas_fiscais;

SELECT * FROM notas_fiscais;

SELECT * FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF
ON NF.NUMERO = INF.NUMERO;

SELECT NF.CPF, NF.DATA_VENDA, INF.QUANTIDADE FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF
ON NF.NUMERO = INF.NUMERO;

SELECT NF.CPF, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO, INF.QUANTIDADE FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF
ON NF.NUMERO = INF.NUMERO;

/* CONSULTA COM VENSAS DE CLIENTES POR MES */
SELECT NF.CPF, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m');

/* LIMITE DE COMPRA POR CLIENTE */
SELECT TV.VPF, TC.NOME, TC.VOLUME_DE_COMPRA AS QUANTIDADE_LIMITE
FROM tabela_de_clientes TC;

/* RELATORIO DE VENDA */
SELECT 
	X.CPF,
	X.NOME, 
	X.MES_ANO, 
	X.QUANTIDADE_VENDAS, 
	X.QUANTIDADE_LIMITE, 
	(X.QUANTIDADE_LIMITE - X.QUANTIDADE_VENDAS) AS DIFERENCA,
CASE 
	WHEN (X.QUANTIDADE_LIMITE - X.QUANTIDADE_VENDAS) < 0 THEN 'INVALIDO'
	ELSE 'VALIDO'
END AS STATUS_VENDA
FROM(
SELECT 
	NF.CPF, 
	TC.NOME, 
	DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO, 
	SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS, 
	MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE 
FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN  tabela_de_clientes TC
ON TC.CPF = NF.CPF
GROUP BY NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m')) X;


/* RELATORIO 2 DE VENDAS */

SELECT 
	VENDA_SABOR.SABOR,
	VENDA_SABOR.ANO,
	VENDA_SABOR.QUANTIDADE,
    (VENDA_SABOR.QUANTIDADE / VENDA_TOTAL.QUANTIDADE) * 100 AS PARTICIPACAO

FROM
(SELECT
	TP.SABOR,
    YEAR(NF.DATA_VENDA) AS ANO,
	SUM(INF.QUANTIDADE) AS QUANTIDADE
FROM tabela_de_produtos TP
	INNER JOIN itens_notas_fiscais INF
	ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
	INNER JOIN notas_fiscais NF
	ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = '2016'
GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)) AS VENDA_SABOR

INNER JOIN

(SELECT
    YEAR(NF.DATA_VENDA) AS ANO,
	SUM(INF.QUANTIDADE) AS QUANTIDADE
FROM tabela_de_produtos TP
	INNER JOIN itens_notas_fiscais INF
	ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
	INNER JOIN notas_fiscais NF
	ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = '2016'
GROUP BY YEAR(NF.DATA_VENDA)) AS VENDA_TOTAL

ON VENDA_SABOR.ANO = VENDA_TOTAL.ANO
ORDER BY VENDA_SABOR.QUANTIDADE DESC;











