CREATE TABLE TAB_FATURAMENTO
(
	DATA_VENDA DATE NULL,
    TOTAL_VENDA FLOAT NULL

);


DELETE FROM TAB_FATURAMENTO;
INSERT INTO TAB_FATURAMENTO
SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) FROM notas_fiscais A
INNER JOIN itens_notas_fiscais B
ON A.NUMERO = B.NUMERO
GROUP BY A.DATA_VENDA;

SELECT * FROM TAB_FATURAMENTO;

DELIMITER //
CREATE TRIGGER TG_CALCULA_FATURAMENTO_INSERT 
AFTER INSERT ON itens_notas_fiscais
FOR EACH ROW BEGIN
	
    DELETE FROM TAB_FATURAMENTO;
	
    INSERT INTO TAB_FATURAMENTO
	SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) FROM notas_fiscais A
	INNER JOIN itens_notas_fiscais B
	ON A.NUMERO = B.NUMERO
	GROUP BY A.DATA_VENDA;
	
END//

SELECT * FROM TAB_FATURAMENTO;


